# Generated by Django 4.2.6 on 2023-10-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_toys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toy',
        ),
    ]
